#! /bin/bash

USAGE="usage: remote [-h] [-r <remote>] [-t <type (fetch or push)> [-b <branch>] file"

AllPRS=0

while getopts ":hpPr:t:b:" opt; do
    case $opt in
        h)
            echo "$USAGE"
            echo "\nOpen the remote repository in the browser."
            exit 0
            ;;
        p)
            PR=1
            shift $(( OPTIND - 1 ));
            ;;
        P)
            AllPRS=1
            shift $(( OPTIND - 1 ));
            ;;
        r)
            REMOTE="$OPTARG"
            shift $(( OPTIND - 1 ));
            ;;
        t)
            TYPE="$OPTARG"
            shift $(( OPTIND - 1 ));
            ;;
        b)
            BRANCH="$OPTARG"
            shift $(( OPTIND - 1 ));
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            echo "$USAGE"
            exit 1
            ;;
    esac
done

DIR=`pwd`

if [[ -n "$1" ]]; then
    FILEDIR=$(dirname `ls -d -F "$1" | sed 's:\/$:/.:'`)
    FILENAME=`echo $1 | sed "s|$FILEDIR/||"`
    cd "$FILEDIR"
    FILEDIR=`pwd`
    CURRENT_DIR="$DIR"
    DIR="$FILEDIR/$FILENAME"
fi

ERR=$(git remote -v 2>&1 >/dev/null)
if [[ -n "$ERR" ]]; then
    echo "ERROR: Not a git repository. Initialize a git repository with 'git init'."
    exit 1
fi

TYPE="fetch"
REMOTES=`git remote -v | grep "$REMOTE" | grep "$TYPE"`

# try with remote as set (or "") and type as set (or "fetch")
# if there's more than one of these, try with remote as origin
# if there's no origin, error with don't know

case $(echo "$REMOTES\n" | wc -l | awk '{print $1}') in
    0)
        echo "ERROR: No remotes are set. Add a remote with 'git remote add <name> <url>'."
        exit 1
        ;;
    1)
        ;;
    *)
        REMOTES=`echo $REMOTES | grep origin`
        if [[ -z "$REMOTES" ]]; then
            echo "ERROR: not sure which remote to open. Specify a remote with '-r <remote>'"
            exit 1
        fi
        ;;
esac
# remove .git suffix
URL=$(echo $REMOTES | awk '{print $2}' | sed 's/\.git$//')

HOST=${URL%%[:/]*}
REPO=${URL##$HOST[:/]}
HOST=${HOST/#git@/"https://"}

if [[ "$ALLPRS" == 1 ]]; then
    open "$HOST/$REPO/pulls"
    exit 0
fi

if [[ -z "$BRANCH" ]]; then
    BRANCH=$(git status | head -1 | sed 's/On branch //')
fi

if [ -z "$CURRENT_DIR" ]; then
    cd "$CURRENT_DIR"
fi

if [[ -n "$PR" ]]; then
    PR=`git pr`
    if [[ -z "$PR" ]]; then
        URL_PATH="compare/$BRANCH?expand=1"
    else
        URL_PATH="pull/$PR"
    fi
else    
        FILE=`echo "$DIR" | sed "s|$(git rev-parse --show-toplevel)||"`
        URL_PATH="tree/$BRANCH$FILE"
fi

URL="$HOST/$REPO/$URL_PATH"
open "$URL"
